export const TextValues = {
  FormTitle: 'Fill the forms',
  AddNewServiceButtonText: 'Add new',
  BackButtonText: 'Back',
  ArrowRight: '→',

  NamePlaceholder: 'Name',
  TypePlaceholder: 'Type',
  AddressPlaceholderLt: 'Latitude',
  AddressPlaceholderLg: 'Longitude',
  DescPlaceholder: 'Description',
  FilePlaceholder: 'Add the photo',

  AboutAppTitle: 'ABOUT APP',
  ServicesTitle: 'MY SERVICES',
  MapTitle: 'SERVICES ON MAP',
  AddNewTitle: 'ADD NEW SERVICE',

  MarkOnMapSwitcher: 'Mark on map',
  AddPhoto: 'Add Photo',
  RemovePhoto: '☒',

  NameReqiuredInputErrTxt: 'Name field is required',
  NameLengthInputErrTxt: 'Name cannot be more than 24',
  TypeReqiuredInputErrTxt: 'Type field is required',
  LatLengthInputErrTxt: 'Latitude must not be more than 180',
  LonLengthInputErrTxt: 'Longitude must not be more than 90',
  DescrLengthInputErrTxt: 'Please, maximum 200 symbols',

  DropdownPlaceholder: 'Select type of service',
  DropdownLabelAuto: 'Auto Services',
  DropdownLabelFood: 'Cafes & Food',
  DropdownLabelSports: 'Sports',
  DropdownLabelHotel: 'Hotels',
  DropdownLabelMall: 'Malls',
  DropdownLabelStore: 'Stores & Shops',
  DropdownLabelPharmacy: 'Pharmacies',
  DropdownLabelFinances: 'Finances & Banks',
  DropdownLabelBeauty: 'Hairdressers & Beauty',
  DropdownLabelEdu: 'Education',
  DropdownLabelOthers: 'Others',
};
