import {SectionDataType} from '@components/ServicesList/types';

export const SERVICES_DATA: SectionDataType = [
  {
    title: 'Cafes',
    data: [
      {
        name: 'Del Mar',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Dionis',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Salateira',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
    ],
  },
  {
    title: 'Gyms',
    data: [
      {
        name: 'Golds Gym',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Sparta',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Adrenalin',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Zevs',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
    ],
  },
  {
    title: 'Barbershops',
    data: [
      {
        name: 'Brock',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'El Cartel',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Jackson',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Underground',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Top Gun',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
    ],
  },
  {
    title: 'Car Repairs',
    data: [
      {
        name: 'Rimbat',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Zapad',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Michelin',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Goodyear',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
      {
        name: 'Bridgestone',
        date: '15082022T12:15:38Z',
        description: 'Little place to have a breakfast and affordable prices',
        address: 'West St. 448',
        location: 'location',
        attach: 'photo',
      },
    ],
  },
];
